# Generated by Django 4.1.5 on 2023-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_site', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('yop', models.IntegerField()),
                ('job_location', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('vacancies', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('drive_location', models.CharField(max_length=100)),
                ('venue_details', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('apply_link', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
