# Generated by Django 4.2 on 2023-07-03 11:25

import autoslug.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Select job role', 'Select job role'), ('App developer', 'App developer'), ('Database administrator', 'Database administrator'), ('Service desk analyst', 'Service desk analyst'), ('Software developer', 'Software developer'), ('Software engineer', 'Software engineer'), ('Software tester', 'Software tester'), ('Web developer', 'Web developer')], default=[('Select job role', 'Select job role'), ('App developer', 'App developer'), ('Database administrator', 'Database administrator'), ('Service desk analyst', 'Service desk analyst'), ('Software developer', 'Software developer'), ('Software engineer', 'Software engineer'), ('Software tester', 'Software tester'), ('Web developer', 'Web developer')], max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_site', models.URLField()),
                ('category', models.CharField(choices=[('Select job category', 'Select job category'), ('Entry Level', 'Entry-Level'), ('Mid level', 'Mid-Level'), ('Senior Level', 'Senior-Level')], default=[('Select job category', 'Select job category'), ('Entry Level', 'Entry-Level'), ('Mid level', 'Mid-Level'), ('Senior Level', 'Senior-Level')], max_length=50)),
                ('salary', models.FloatField()),
                ('yop', models.CharField(max_length=50)),
                ('job_location', models.CharField(choices=[('Select job location', 'Select job location'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Andheri', 'Andheri')], default=[('Select job location', 'Select job location'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Andheri', 'Andheri')], max_length=50)),
                ('qualification', models.CharField(choices=[('Select degree', 'Select degree'), ('Any Degree', 'Any Degree'), ('M.E/M.Tech/M.S', 'M.E/M.Tech/M.S'), ('B.E/B.Tech', 'B.E/B.Tech'), ('MBA', 'MBA'), ('Diploma', 'Diploma')], default=[('Select degree', 'Select degree'), ('Any Degree', 'Any Degree'), ('M.E/M.Tech/M.S', 'M.E/M.Tech/M.S'), ('B.E/B.Tech', 'B.E/B.Tech'), ('MBA', 'MBA'), ('Diploma', 'Diploma')], max_length=50)),
                ('vacancies', models.IntegerField()),
                ('experience', models.CharField(choices=[('Select experience', 'Select experience'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], default=[('Select experience', 'Select experience'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], max_length=50)),
                ('drive_location', models.CharField(max_length=100)),
                ('venue_details', models.TextField(blank=True, max_length=200, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('apply_link', models.URLField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('publisher_name', models.CharField(max_length=50)),
                ('updated_by', models.CharField(default=None, max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='role', unique=True)),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(default='Guest', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
