# Generated by Django 4.1.5 on 2023-03-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_modified',
        ),
    ]
