# Generated by Django 4.1.5 on 2023-03-04 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_job_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 8, 10, 47, 124464), editable=False),
            preserve_default=False,
        ),
    ]
