# Generated by Django 4.1.5 on 2023-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_job_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
