# Generated by Django 4.1.5 on 2023-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_job_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_site',
            field=models.URLField(),
        ),
    ]
