# Generated by Django 4.1.5 on 2023-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_job_apply_link_alter_job_company_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
