# Generated by Django 4.1.5 on 2023-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_job_job_id_alter_job_vacancies_alter_job_yop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='yop',
            field=models.IntegerField(max_length=4),
        ),
    ]
