# Generated by Django 4.1.5 on 2023-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_job_yop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='yop',
            field=models.CharField(max_length=50),
        ),
    ]
