# Generated by Django 4.1.5 on 2023-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_job_yop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('entry', 'Entry-Level'), ('mid', 'Mid-Level'), ('senior', 'Senior-Level')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5+')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('App developer', 'App developer'), ('Database administrator', 'Database administrator'), ('Service desk analyst', 'Service desk analyst'), ('Software developer', 'Software developer'), ('Software engineer', 'Software engineer'), ('Software tester', 'Software tester'), ('Web developer', 'Web developer')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='venue_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='yop',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4),
        ),
    ]
