# Generated by Django 4.1.5 on 2023-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_job_category_alter_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Entry Level', 'Entry-Level'), ('Mid level', 'Mid-Level'), ('Senior Level', 'Senior-Level')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Andheri', 'Andheri')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('App developer', 'App developer'), ('Database administrator', 'Database administrator'), ('Service desk analyst', 'Service desk analyst'), ('Software developer', 'Software developer'), ('Software engineer', 'Software engineer'), ('Software tester', 'Software tester'), ('Web developer', 'Web developer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='yop',
            field=models.CharField(max_length=4),
        ),
    ]
