# Generated by Django 4.1.5 on 2023-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_job_category_alter_job_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='venue_details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
