# Generated by Django 4.1.5 on 2023-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_job_qualification_alter_job_role_alter_job_yop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Entry Level', 'Entry-Level'), ('Mid level', 'Mid-Level'), ('Senior Level', 'Senior-Level')], default='E', max_length=50),
        ),
    ]
