# Generated by Django 4.1.5 on 2023-03-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Select job category', 'Select job category'), ('Entry Level', 'Entry-Level'), ('Mid level', 'Mid-Level'), ('Senior Level', 'Senior-Level')], default=[('Select job category', 'Select job category'), ('Entry Level', 'Entry-Level'), ('Mid level', 'Mid-Level'), ('Senior Level', 'Senior-Level')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Select experience', 'Select experience'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(choices=[('Select job location', 'Select job location'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Andheri', 'Andheri')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('Select degree', 'Select degree'), ('Any Degree', 'Any Degree'), ('M.E/M.Tech/M.S', 'M.E/M.Tech/M.S'), ('B.E/B.Tech', 'B.E/B.Tech'), ('MBA', 'MBA'), ('Diploma', 'Diploma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('Select job role', 'Select job role'), ('App developer', 'App developer'), ('Database administrator', 'Database administrator'), ('Service desk analyst', 'Service desk analyst'), ('Software developer', 'Software developer'), ('Software engineer', 'Software engineer'), ('Software tester', 'Software tester'), ('Web developer', 'Web developer')], default=[('Select job role', 'Select job role'), ('App developer', 'App developer'), ('Database administrator', 'Database administrator'), ('Service desk analyst', 'Service desk analyst'), ('Software developer', 'Software developer'), ('Software engineer', 'Software engineer'), ('Software tester', 'Software tester'), ('Web developer', 'Web developer')], max_length=50),
        ),
    ]
