# Generated by Django 4.1.5 on 2023-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_job_category_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Select experience', 'Select experience'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], default=[('Select experience', 'Select experience'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(choices=[('Select job location', 'Select job location'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Andheri', 'Andheri')], default=[('Select job location', 'Select job location'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Navi mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Andheri', 'Andheri')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('Select degree', 'Select degree'), ('Any Degree', 'Any Degree'), ('M.E/M.Tech/M.S', 'M.E/M.Tech/M.S'), ('B.E/B.Tech', 'B.E/B.Tech'), ('MBA', 'MBA'), ('Diploma', 'Diploma')], default=[('Select degree', 'Select degree'), ('Any Degree', 'Any Degree'), ('M.E/M.Tech/M.S', 'M.E/M.Tech/M.S'), ('B.E/B.Tech', 'B.E/B.Tech'), ('MBA', 'MBA'), ('Diploma', 'Diploma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='yop',
            field=models.BooleanField(max_length=50),
        ),
    ]
