# Generated by Django 4.1.5 on 2023-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_job_experience_alter_job_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='yop',
            field=models.CharField(max_length=50),
        ),
    ]
